---
title: "Client Report - Longevity of Baseball Players"
subtitle: "Unit 2 Task 2"
author: "Camila Rojas"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd 
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
sqlite_file = 'lahmansbaseballdb.sqlite'
# this file must be in the same location as your .qmd or .py file
con = sqlite3.connect(sqlite_file)
```

## QUESTION 1

__Write an SQL query that pulls in the batting average table. Then, with Python Pandas code create a dataframe that contains playerID, yearID, and batting average for players with at least 10 at bat that year. Sort the dataframe from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.__

This table shows the top 5 batting averages for players with at least 10 at-bats. The highest is nymanny01 with 0.643 in 1974. Since it’s only players with 10+ at-bats, the averages can still look really high.

```{python}
# Execute an SQL query to pull in the data
q = """SELECT *
        FROM batting
    """
df_batting = pd.read_sql_query(q, con)
```

```{python}
# Now use pandas code to work with the 'df_batting' data frame and complete the task

df = df_batting

df["BatAvg"] = df["H"] / df["AB"]

df = df.loc[df["AB"] >= 10, ["playerID", "yearID", "BatAvg"]]

df = df.sort_values("BatAvg", ascending=False)

df = df.head(5)

df = df.sort_values("playerID")

df

```

## QUESTION 2

__Now use Python Pandas to calculate the batting average for players over their entire careers (all years combined). Only include players with at least 100 at bats over their entire career, and print the top 5 results.__

This table shows the top 5 career batting averages with at least 100 total at-bats. Cobbty01 has the highest average at 0.366. Because this is based on a whole career, the results are more realistic.

```{python}

df = df_batting

df = df.groupby("playerID", as_index=False).agg({
    "H": "sum",
    "AB": "sum"
})

df["BatAvg"] = df["H"] / df["AB"]

df = df.loc[df["AB"] >= 100, ["playerID", "BatAvg"]]

df = df.sort_values("BatAvg", ascending=False)

df = df.head(5)

df = df.sort_values("playerID")

df

```


