---
title: "Client Report - Missing Data and JSON"
subtitle: "Unit 3 Task 1"
author: "Camila Rojas"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd 
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pd.read_json("https://github.com/byuidatascience/data4missing/raw/master/data-raw/flights_missing/flights_missing.json")
```

## QUESTION 1

__Fix all of the varied missing data types in the data to be consistent: use np.nan to represent missing value.__ In your report include one record example (one row) from your clean data, in the raw JSON format. Your example should display at least one missing value so that we can verify it was done correctly. (Note: JSON will convert NaN's to "null"). Describe your process for finding values that needed to be changed, and how you changed them.__ 

I checked for missing values using isna() and isna().sum(). I saw that some missing data was written as values like -999 or "NA" instead of real NaN. I used replace() to change those to np.nan so all missing values are the same. Then I exported one row to JSON, and you can see a missing value shows up as null (for example, num_of_delays_late_aircraft is null).

```{python}
# Include and execute your code here
url = "https://github.com/byuidatascience/data4missing/raw/master/data-raw/flights_missing/flights_missing.json"
delays_json = pd.read_json(url)

delays_clean = delays_json

delays_clean.isna().sum()

delays_clean = delays_clean.replace({"": np.nan, "NA": np.nan, "N/A": np.nan, "None": np.nan, "null": np.nan, -999: np.nan})

delays_clean.isna().sum()

example_row = delays_clean.iloc[0:1]

example_row.to_json(orient="records")

```
