---
title: "Client Report - Show me!"
subtitle: "Unit 4 Task 3"
author: "Camila Rojas"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import pandas as pd 
import numpy as np
from lets_plot import *
from sklearn.datasets import load_wine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# import your data here using pandas and the URL
df = pd.read_csv("https://github.com/byuidatascience/data4dwellings/raw/master/data-raw/dwellings_ml/dwellings_ml.csv")
df1 = df
```
```{python}
X = df1.select_dtypes(include=[np.number]).drop(columns=['yrbuilt','before1980'])
y = df1['before1980']

X_train, X_test, y_train, y_test = train_test_split(X, y, train_size=0.2, random_state=42)

myclassifier = RandomForestClassifier(random_state=42)
myclassifier.fit(X_train, y_train)
```
```{python}
y_pred = myclassifier.predict(X_test)

```


## QUESTION 1

__Create 2-3 charts that evaluate the relationships between each of the top 2 or 3 most important variables (as found in Unit 4 Task 2) and the year the home was built.__ Describe what you learn from the charts about how that variable is related to year built.   

_From the charts, we can see how the most important variables relate to the year the house was built. For livearea, the graph shows that newer houses tend to have larger living areas, especially after around 1980. For gartype_Att, the values increase over time, which means attached garages are more common in newer houses. For arcstyle_ONE-STORY, the graph goes down after around 1950, so one-story houses are less common in newer homes. Overall, these variables change with time, which explains why they are important for predicting the year built._

```{python}
# Include and execute your code here
myclassifier.feature_importances_
X_train.columns

df = pd.DataFrame({'importance':myclassifier.feature_importances_,
'feature':X_train.columns}).sort_values('importance', ascending=False)

df2 = df.head(3)
df2
```
```{python}
#df_livefix = df1
#df_livefix["livearea"] = (df1["livearea"]//100)*100
#(
#  ggplot(df_livefix, mapping = aes(x = "livearea", y = "before1980", color = "before1980"))+
#  scale_x_continuous(limits=(0,3000))+
#  geom_count()
#)
```
```{python}
p=(
    ggplot(data = df2)
    +geom_bar(aes(y='feature', x = 'importance'), stat = 'identity')+
    labs(
      title= 'Top 5 most important features'
    )
)
p
```

```{python}
#p2 = (
#    ggplot(df1, aes(x='yrbuilt', y='livearea')) +
#   geom_point(alpha=0.01, size=3) +
#    labs(x='Year Built', y='Living Area', title='Living Area vs Year Built')+
#    geom_smooth(method='lm')
#)
#p2
```

```{python}
p4= (
    ggplot(df1, aes(x='yrbuilt', y='livearea')) +
    geom_smooth(method="loess",color="red",span=0.3)
)
p4
```
```{python}
p5= (
    ggplot(df1, aes(x='yrbuilt', y='gartype_Att')) +
    geom_smooth(method="loess",color="red",span=0.3)
)
p5
```

```{python}
p6= (
    ggplot(df1, aes(x='yrbuilt', y='arcstyle_ONE-STORY')) +
    geom_smooth(method="loess",color="red",span=0.3)
)
p6
```

## QUESTION 2

__Create at least one other chart to examine a variable(s) you thought might be important but apparently was not. The chart should show its relationship to the year built.__ Describe what you learn from the chart about how that variable is related to year built. Explain why you think it was not (very) important in the model.

_From the chart, condition_VGood does not show a clear relationship with the year built because the line stays almost flat. This means that houses in very good condition can be from any year, not just newer or older ones. Because of this, the model does not use this variable as much. It is not very helpful for predicting when a house was built._

```{python}
# Include and execute your code here
p6= (
    ggplot(df1, aes(x='yrbuilt', y='condition_VGood')) +
    geom_smooth(method="loess",color="red",span=0.3)
)
p6

```
